import type { AgentResult } from "../../../packages/contracts/src/agent";
import type { ChatMessage } from "../../../services/model-router/src/client";
import type { AgentHandler } from "../../../services/agents/src/runtime";

/** The one thing the handler needs from a model client (so tests can hand in a fake). */
export interface ChatModel {
  chat(messages: ChatMessage[], options?: { maxTokens?: number }): Promise<{ text: string; model: string }>;
}

const MAX_FINDINGS = 8;
const MAX_FINDING_LENGTH = 400;

/** Splits a model answer into short findings: one per non-empty line, bullets and numbering removed. */
export function toFindings(text: string): string[] {
  return text
    .split(/\r?\n/)
    .map((line) => line.replace(/^\s*(?:[-*•]|\d+[.)])\s+/, "").trim())
    .filter(Boolean)
    .slice(0, MAX_FINDINGS)
    .map((line) => (line.length > MAX_FINDING_LENGTH ? `${line.slice(0, MAX_FINDING_LENGTH)}…` : line));
}

const SYSTEM_PROMPT = [
  "You are the coding agent of KHAN OS, a software engineering orchestrator.",
  "You are given one step of a plan. You have NO access to files, a shell or the network:",
  "you can only reason about the step and answer in text.",
  "Answer with 3 to 6 short, concrete lines, one finding or action per line, no preamble."
].join(" ");

/**
 * A coding agent backed by a real model. It analyses and proposes; it does not touch the workspace,
 * and its first finding says so. A model failure throws, which the runtime records as a failed step.
 */
export function createModelCodingHandler(model: ChatModel): AgentHandler {
  return async (step, context): Promise<AgentResult> => {
    const earlier = ((context.inputs.agentResults as AgentResult[] | undefined) ?? [])
      .map((result) => `- ${result.summary}`)
      .join("\n");
    const { text, model: modelId } = await model.chat([
      { role: "system", content: SYSTEM_PROMPT },
      {
        role: "user",
        content: [`Goal: ${context.goal}`, `Current step (${step.id}): ${step.title}`, earlier ? `Earlier steps:\n${earlier}` : ""].filter(Boolean).join("\n\n")
      }
    ]);

    const findings = toFindings(text);
    if (findings.length === 0) throw new Error("The model answer contained no findings");
    return {
      status: "success",
      // QA checks that results mention the goal, so the summary always does.
      summary: `Executed coding agent step '${step.id}' for goal: ${context.goal}`,
      findings: [`Model-generated by ${modelId}; no files were changed and no tests were run.`, ...findings]
    };
  };
}
